var http = require('http')
var fs = require('fs')
const { type } = require('os')
var server = http.createServer(function(req,res){
    console.log('request made was:',res.url)
    res.writeHead(200,{'Content-type':'text/html'})
    myReadStream = fs.createReadStream(__dirname +'/index.html','utf-8')
    myReadStream.pipe(res)
})
server.listen(3000,'127.0.0.1')
console.log('HTML file rendered in port number 3000')